workflows:
  Firebase App Distribution Workflow:
    environment:
      # Other environment variables specific to your project can be defined here
    ios:
      apple_app_store_connect:
        issuer_id: "69a6de82-0d8b-47e3-e053-5b8c7c11a4d1"
        key_identifier: "9H3T4F5LSU"
        private_key: Encrypted(Z0FBQUFBQmhVallHUy1TaVBwcnVzWkwwbk9lb0FhUm0yOGZCa3pKVkpaWXgxYzRIdHBDQlVNUlVNNm9BQ2U3T0x3dU1hNWV6SklPNDBVeUJfYVNnTFREeHpneUJ2Z2dSRzl6WUxySUN0aU5aOGpYR3VRMURXcnRTX2JEMUgwUWtyc0U4WmlDRy1aa0dKanZ3alZWXy0wU1lVMHZsY25rdmxIbmIzXzRCMmdOT0dPTjRENnVKTUFpZDhERU5WXzZXem56MlMzQnp2Yy1fQmZFcTNYNjNFTl9aU0xhOXFGUVA4YTdZWmwtbHhGMFFZcWtpWGk1ZzNuQ2UtNHBDcFAzQTE0dU9uRHFhMDZQaEpkZjdvMnhpMWJyWnpTeTNfeWRGd1pnTmhkdVhuWjFFT2VPVEhfeURLeXFVWHROQjRkQzZfeGgtS2lJbUFMc21rRzh6Mm9SVWhrRmlkLWd3X0luME1KeGVOc3JIbnAzRF9xNUp4VmtMOHJXTTVLalVOWjNpZDA0V2dlMW50NDVqSF83U2pKNUNXVTRPVWRrWVkzRktwZV9CSXl2V0M5UjlEWkpGWWVfOVdlRT0=)
        # Other iOS code signing settings can be defined here
